services:
  - type: web
    name: velocity-retail-backend
    runtime: node
    rootDir: backend
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_ACCESS_EXPIRES
        value: 15m
      - key: JWT_REFRESH_EXPIRES
        value: 7d
      - key: CLIENT_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: qwen/qwen3.8-27b
      - key: CLOUDINARY_CLOUD_NAME
        value: yqs5ezyx
      - key: CLOUDINARY_API_KEY
        value: "945519752313942"
      - key: CLOUDINARY_API_SECRET
        sync: false
